apiVersion: v1
kind: Secret
metadata:
  name: bind9-dns-secrets
  namespace: bind9-dns
type: Opaque
data:
  # Create a base64 encoded string of the client_app_id, client_app_secret, and tenant_id
  # from App Registration in Entra ID and Azure Monitor (DCE/DCR)
  # echo -n '[value1]' | base64
  bind9_client_app_id: 'CLIENT_APP_ID_BASE64_VALUE_GOES_HERE'
  bind9_client_app_fluentbit_secret: 'FLUENTBIT_SECRET_BASE64_VALUE_GOES_HERE'
  azure_tenant_id: 'TENANT_ID_BASE64_VALUE_GOES_HERE'
  bind9_data_collection_endpoint: 'DATA_COLLECTION_ENDPOINT_BASE64_VALUE_GOES_HERE'
  bind9_data_collection_rule_id: 'DATA_COLLECTION_RULE_BASE64_VALUE_GOES_HERE'
