apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-fluent-bit-sc-config
  namespace: bind9-dns
  labels:
    app: fluent-bit-bind9-dns
data:
  # Configuration files: server, input, filters and output
  # There MUST be a space between [SERIVCE] and @INCLUDE statements
  # There MUST be a space between @INCLUDE and configuration file names
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off

    @INCLUDE input-bind9.conf
    @INCLUDE filter-bind9.conf
    @INCLUDE output-stdout.conf
    @INCLUDE output-azure-log-ingestion-api.conf

  input-bind9.conf: |
    [INPUT]
        Name                tail
        Tag                 bind9
        Key                 RawData
        Path                /var/log/named/*.log
        DB                  /tmp/bind9_flb.db
        Mem_Buf_Limit       5MB
        Refresh_Interval    10
  filter-bind9.conf: |
    [FILTER]
        Name                modify
        Match               bind9
        Add                 System ${HOSTNAME}
  output-stdout.conf: |
    # Change 'sample' to bind9 to see output via [kubectl logs -f fluent-bit-bind9-dns-xxxxx -n bind9-dns]
    [OUTPUT]
        Name                stdout
        Match               sample
        Format              json_lines
  output-azure-log-ingestion-api.conf: |
    [OUTPUT]
        Name                azure_logs_ingestion
        Match               bind9
        client_id           ${bind9_client_app_id}
        client_secret       ${bind9_client_app_fluentbit_secret}
        tenant_id           ${azure_tenant_id}
        dce_url             ${bind9_data_collection_endpoint}
        dcr_id              ${bind9_data_collection_rule_id}
        table_name          fluentbit_bind9_dns_CL
        time_generated      true
        Compress            true

# https://kubernetes.io/docs/concepts/configuration/configmap/
immutable: true
